# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1ba9d2920cc38be8d94ba7d4fb58e6aa19c1f08474505797447278064063dad506e407869d4700d4c24b28d9977d6ef780d9ed87af5acfc1558d2c447274694

test:
  secret_key_base: 9e8724c695454d7ff78337e6216a8c9999bb02076682b33b1b68e4be1e5f8b280654a3c897fa4e629a4a8059bf4d52bf00045593a65386da5345976b18df8fcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
